name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - shell: bash
      run: |
        pm2 stop avwxbotpi
        node ~/Documents/projects/lights/turnoff.js
        pm2 delete avwxbotpi
        rm -rf ~/Documents/projects/avwxbot
        mkdir ~/Documents/projects/avwxbot
        cp -r * ~/Documents/projects/avwxbot
        cd ~/Documents/projects/avwxbot/
        pm2 start index.js --name avwxbotpi
        pm2 save
