name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - shell: bash
      run: pm2 stop avwxbotpi
    - shell: bash
      run: node ~/Documents/projects/lights/turnoff.js
    - shell: bash
      run: pm2 delete avwxbotpi
    - shell: bash
      run: pm2 save
    - shell: bash
      run: rm -rf ~/Documents/projects/avwxbot
    - shell: bash
      run: mkdir ~/Documents/projects/avwxbot
    - shell: bash
      run: cp -r ~/actions-runner/_work/avwxbotpi/avwxbotpi/* ~/Documents/projects/avwxbot
    - shell: bash
      run: pm2 start ~/Documents/projects/avwxbot/index.js --name avwxbotpi
    - shell: bash
      run: pm2 save